---
- - DocumentCloud: This week's top journalism resource
  - http://www.melbournepressclub.com/news/resources/document-cloud
  - Melbourne Press Club
  - 2011-07-12
- - DocumentCloud: Not Just for Journalists?
  - http://chronicle.com/blogs/profhacker/documentcloud-not-just-for-journalists/34528
  - Chronicle of Higher Education
  - 2011-07-08
- - With its newest round of Knight funding, DocCloud will figure out how to scale reader annotations
  - http://www.niemanlab.org/2011/07/with-its-newest-round-of-knight-funding-doccloud-will-figure-out-how-to-scale-reader-annotations/
  - Neiman Journalism Lab
  - 2011-07-05
- - Direct Access To The Documents Behind The News
  - http://www.makeuseof.com/tag/documentcloud-direct-access-documents-news/
  - Make Use Of
  - 2011-05-04
- - Las Vegas Sun Pulitzer finalists explain how they turned data into Web gold
  - http://www.poynter.org/latest-news/als-morning-meeting/128672/las-vegas-sun-pulitzer-finalists-explain-how-they-turned-data-into-web-gold/
  - Poynter
  - 2011-04-22
- - Search Public Documents Online With Document Cloud
  - http://www.observer.com/2011/tech/search-public-documents-online-document-cloud
  - New York Observer
  - 2011-01-26
- - Putting Source Documents Online? DocumentCloud can Enhance Reporting, Engagement
  - http://www.knightdigitalmediacenter.org/leadership_blog/comments/20101119_putting_source_documents_online_documentcloud_can_enhance_reportin/
  - Knight Digital Media Center
  - 2010-11-19
- - A Tale of Two Documents
  - http://www.propublica.org/nerds/item/a-tale-of-two-documents
  - The ProPublica Nerd Blog
  - 2010-10-08
- - Tech Tip: DocumentCloud for Librarians
  - http://newslib.blogspot.com/2010/09/tech-tip-documentcloud-for-librarians.html
  - News Library News
  - 2010-09-22
- - Let me introduce you to Document Cloud
  - http://www.slaw.ca/2010/07/20/document-cloud/
  - SLAW
  - 2010-07-20
- - New investigative journalism tool debuts in Montana
  - http://missoulanews.bigskypress.com/missoula/cloud-nine/Content?oid=1273254
  - Missoula Independent
  - 2010-07-08
- - Tribune becomes first Montana newspaper to employ DocumentCloud technology
  - http://mtlowdown.blogspot.com/2010/07/tribune-becomes-first-montana-newspaper.html
  - The Lowdown, News and Notes from the Montana Capital
  - 2010-07-06
- - WBEZ Uses New Tool to Share Public Documents
  - http://blogs.vocalo.org/bhealy/2010/05/wbez-uses-new-tool-to-share-public-documents/22852
  - Vocalo / Chicago Public Radio
  - 2010-05-12
- - DocumentCloud aims to release a public beta in March 2010
  - http://blogs.journalism.co.uk/editors/2010/01/06/documentcloud-aims-to-release-a-public-beta-in-march-2010/
  - Journalism.co.uk
  - 2010-01-06
- - Thomson Reuters Celebrates Ten Innovative Sites and Services Using OpenCalais
  - http://damtrends.com/2009/10/thomson-reuters-celebrates-ten-innovative-sites-services-opencalais/
  - DAMTrends
  - 2009-10-21
- - DocumentCloud still looking for more collaborators; Amazon Web Services set to partner
  - http://blogs.journalism.co.uk/editors/2009/09/28/documentcloud-still-looking-for-more-collaborators-amazon-web-services-set-to-partner/
  - Journalism.co.uk
  - 2009-09-28
- - OpenCalais joins DocumentCloud, set to host a wealth of primary sources
  - http://www.editorsweblog.org/multimedia/2009/09/opencalais_joins_documentcloud_set_to_ho.php
  - Editors Weblog
  - 2009-09-25
- - The Atlantic, The New Yorker, Mother Jones, WNYC, More Join Data Archive Experiment DocumentCloud
  - http://www.observer.com/2009/media/atlantic-new-yorker-mother-jones-wnyc-more-join-data-archive-experiment-documentcloud
  - The New York Observer
  - 2009-09-24
- - Thomson Reuters partners KNC winner DocumentCloud
  - http://www.journalism.co.uk/2/articles/535928.php
  - Journalism.co.uk
  - 2009-09-24
- - More News from DocumentCloud
  - http://www.knightblog.org/more-news-from-documentcloud/
  - Knightblog
  - 2009-09-24
- - DocumentCloud adds impressive list of investigative-journalism outfits
  - http://www.niemanlab.org/2009/09/documentcloud-adds-impressive-list-of-investigative-journalism-outfits/
  - Nieman Journalism Lab
  - 2009-09-24
- - "\xE2\x80\x9CDon't leave me alone in a room with CloudCrowd\xE2\x80\x9D"
  - http://ruby5.envylabs.com/episodes/11-episode-10-september-15-2009
  - Ruby5 Podcast
  - 2009-09-15
- - "Coming soon: Data mining made easier"
  - http://niemanwatchdog.org/index.cfm?fuseaction=Showcase.view&showcaseid=00111
  - Nieman Watchdog
  - 2009-07-11
- - Knight Grantee Points to One Future of Public Information Sharing
  - http://techpresident.com/blog-entry/knight-grantee-points-one-future-public-information-sharing
  - TechPresident
  - 2009-06-25
- - Times, ProPublica Journos Get $719,500 for DocumentCloud
  - http://www.observer.com/2009/media/whos-saving-journalism
  - The New York Observer
  - 2009-06-18
- - "Archived Chat: ProPublica, NYT Team on How DocumentCloud Will Improve Investigations"
  - http://www.poynter.org/column.asp?id=101&aid=165353
  - Poynter Online
  - 2009-06-18
- - "What is DocumentCloud? Answers from Umansky and Pilhofer "
  - http://www.journalism.co.uk/2/articles/534819.php
  - Journalism.co.uk
  - 2009-06-18
- - Knight Foundation Awards $5.1 Million To News Challenge Winners
  - http://www.mediabistro.com/fishbowlny/awards/knight_foundation_awards_51_million_to_news_challenge_winners_119339.asp
  - FishbowlNY
  - 2009-06-18
- - "Knight News Challenge Winners Named\xE2\x80\x94Get $5.1 Million"
  - http://www.editorandpublisher.com/eandp/news/article_display.jsp?vnu_content_id=1003985130
  - Editor & Publisher
  - 2009-06-17
- - The Knight Foundation makes some bets on the future
  - http://blogs.chicagoreader.com/news-bites/2009/06/17/knight-foundation-makes-some-bets-future/
  - Chicago Reader
  - 2009-06-17
- - DocumentCloud Gets Funding to Create Research Memory Bank in the Sky
  - http://www.readwriteweb.com/archives/documentcloud_gets_funding_to_create_research_memo.php
  - ReadWriteWeb
  - 2009-06-17
- - NY Times/ProPublica Team Wins $719,000 Knight News Challenge Grant
  - http://www.wired.com/epicenter/2009/06/ny-timespropublica-team-wins-719000-knight-news-challenge-grant/
  - Wired
  - 2009-06-17
- - "Knight News Challenge: A grant to DocumentCloud promises a data boost for investigative journalism"
  - http://www.niemanlab.org/2009/06/knight-news-challenge-a-grant-to-documentcloud-promises-a-data-boost-for-investigative-journalism/
  - Nieman Journalism Lab
  - 2009-06-17
- - ProPublica, NY Times Team Wins Knight News Challenge Grant for Investigative Document Site
  - http://www.poynter.org/column.asp?id=101&aid=165353
  - Poynter Online
  - 2009-06-17
- - Filling  in the Blanks on DocumentCloud
  - http://www.ojr.org/ojr/people/eulken/200901/1632/
  - Online Journalism Review
  - 2009-01-28
- - "Knight News Challenge 2009: The Collaborative DocumentCloud"
  - http://www.journalism.co.uk/2/articles/532990.php
  - Journalism.co.uk
  - 2008-12-05
- - "DocumentCloud: The Innovation $1m in Knight money could buy"
  - http://www.niemanlab.org/2008/11/documentcloud-the-innovation-1m-in-knight-money-could-buy/
  - Nieman Journalism Lab
  - 2008-11-19
