partners:
   - - Gotham Gazette
     - http://gothamgazette.com
   - - National Security Archive
     - http://gwu.edu/~nsarchiv
   - - New York Times
     - http://nytimes.com
   - - ProPublica
     - http://propublica.org
   - - Talking Points Memo
     - http://talkingpointsmemo.com
contributors:
   - - 13WMAZ
     - http://wmaz.com
   - - 60 Minutes
     - http://www.cbsnews.com/sections/60minutes/main3415.shtml
   - - Accent
     - http://theaccent.org/
   - - ACLU National Security Project
     - http://aclu.org/national-security
   - - The Advocate
     - http://www.stamfordadvocate.com
   - - Albany Times-Union
     - http://www.timesunion.com
   - - AnnArbor.com
     - http://annarbor.com
   - - Arizona Republic
     - http://azcentral.com
   - - Asbury Park Press
     - http://www.app.com
   - - Atlanta Journal-Constitution
     - http://ajc.com
   - - The Atlantic
     - http://theatlantic.com
   - - The Bay Citizen
     - http://www.baycitizen.org/
   - - Better Government Association
     - http://www.bettergov.org
   - - Black Hills Knowledge Network
     - http://myhills.com/
   - - Borderzine
     - http://borderzine.com
   - - Boston Globe
     - http://boston.com/bostonglobe
   - - Boston Review
     - http://bostonreview.net/
   - - The Bureau of Investigative Journalism
     - http://www.tbij.com
   - - California Watch
     - http://californiawatch.org
   - - CBC News
     - http://CBCNews.ca
   - - Center for Democracy and Technology / OpenCRS
     - http://opencrs.com
   - - Center for Investigative Reporting
     - http://centerforinvestigativereporting.org
   - - Center for Public Integrity
     - http://publicintegrity.org
   - - Centre for Investigative Journalism, City University London
     - http://www.tcij.org/
   - - The Charleston Gazette
     - http://wvgazette.com
   - - Chicago Public Radio
     - http://chicagopublicradio.org
   - - Chicago Talks
     - http://www.chicagotalks.org
   - - Chicago Tribune
     - http://chicagotribune.com
   - - Chronicle of Philanthropy
     - http://www.philanthropy.com
   - - Cincinnati Enquirer
     - http://news.cincinnati.com
   - - Circle of Blue
     - http://circleofblue.org
   - - The Coast
     - http://www.thecoast.ca/
   - - Coastsider
     - http://coastsider.com/
   - - Columbia Daily Tribune
     - http://www.columbiatribune.com
   - - Columbia Missourian
     - http://www.columbiamissourian.com
   - - Commercial Appeal
     - http://www.commercialappeal.com
   - - Connecticut Post
     - http://www.ctpost.com
   - - The Crime Report
     - http://www.thecrimereport.org
   - - Dallas Morning News
     - http://dallasnews.com
   - - The Daily Californian
     - http://www.dailycal.org
   - - Danbury News-Times
     - http://www.newstimes.com
   - - Dark Acres
     - http://www.darkacres.com
   - - Dart Center for Journalism & Trauma
     - http://dartcenter.org
   - - Dateline Carolina
     - http://www.datelinecarolina.org/
   - - Democrat and Chronicle
     - http://www.DemocratAndChronicle.com
   - - Des Moines Register
     - http://www.dmreg.com
   - - DeWitt Wallace Center for Media and Democracy
     - http://dewitt.sanford.duke.edu/
   - - Deutsche Presse-Agentur
     - http://www.dpa.de
   - - Diamond Bar Patch
     - http://diamondbar.patch.com
   - - Digital Advance NZ
     - http://digitaladvance.co.nz
   - - Edmonton Journal
     - http://www.edmontonjournal.com/
   - - Electronic Frontier Foundation
     - http://www.eff.org
   - - El Paso Times
     - http://elpasotimes.com
   - - Epoch Times
     - http://www.theepochtimes.com/
   - - Erie Times-News
     - http://goerie.com/
   - - The Erie Wire
     - http://www.eriewire.org
   - - Fire Dog Lake
     - http://firedoglake.com
   - - The Florida Independent
     - http://floridaindependent.com/
   - - Foodless
     - http://5dollardinner.tumblr.com
   - - Forbes
     - http://forbes.com
   - - Fort Collins Coloradoan
     - http://www.coloradoan.com
   - - Free Government Information
     - http://freegovinfo.info/
   - - Frontline
     - http://www.pbs.org/wgbh/pages/frontline
   - - The Gadsden Times
     - http://www.gadsdentimes.com/
   - - The Gainesville Sun
     - http://www.gainesville.com
   - - Gapers Block
     - http://gapersblock.com
   - - Great Falls Tribune
     - http://greatfallstribune.com
   - - Greenwich Time
     - http://www.greenwichtime.com
   - - Health News Florida
     - http://www.healthnewsflorida.org/
   - - Hearst Papers
     - http://www.hearst.com/newspapers
   - - Help Me Investigate
     - http://helpmeinvestigate.com/
   - - Homicide Watch D.C.
     - http://homicidewatch.org/
   - - Houston Chronicle
     - http://chron.com
   - - Huffington Post Investigative Fund
     - http://huffpostfund.org
   - - Investigate West
     - http://invw.org
   - - Investigative Reporting Workshop at American University
     - http://investigativereportingworkshop.org
   - - The Journal-Standard
     - http://www.journalstandard.com
   - - JURIST
     - http://jurist.org/
   - - KHI News Service
     - http://www.khi.org/
   - - KRCG 13
     - http://www.connectmidmissouri.com
   - - Las Vegas Sun
     - http://www.lasvegassun.com
   - - Lawrence Journal-World
     - http://www.ljworld.com/
   - - The Lens
     - http://thelensnola.org
   - - LinkTV
     - http://linktv.org
   - - Living on Earth
     - http://www.loe.org
   - - Los Angeles Times
     - http://latimes.com
   - - Maryland Reporter
     - http://marylandreporter.com
   - - McClatchy Washington Bureau
     - http://www.mcclatchydc.com
   - - Media Coop
     - http://www.mediacoop.ca/
   - - Miami Herald
     - http://miamiherald.com
   - - Military Times
     - http://militarytimes.com/
   - - Milwaukee Journal Sentinel
     - http://www.journalsentinel.com
   - - Minnesota Public Radio News
     - http://minnesota.publicradio.org/
   - - MinnPost
     - http://minnpost.com
   - - Montana Watchdog
     - http://montana.watchdog.org/
   - - Mother Jones
     - http://motherjones.com
   - - msnbc.com
     - http://msnbc.msn.com
   - - Muck Rock
     - http://www.muckrock.com
   - - National Public Radio
     - http://npr.org
   - - National Security Journalism Initiative (Medill)
     - http://medillnsj.org/
   - - NewsHour
     - http://pbs.org/newshour
   - - The News Journal
     - http://www.delawareonline.com
   - - News Northwest
     - http://newsnw.org
   - - The New Yorker
     - http://newyorker.com
   - - North Coast Journal
     - http://www.northcoastjournal.com/
   - - Oakland Local
     - http://oaklandlocal.com
   - - Ocala Star-Banner
     - http://www.ocala.com/
   - - The Oklahoman
     - http://www.newsok.com
   - - OpenFile
     - http://openfile.ca
   - - Omaha World-Herald
     - http://www.omaha.com
   - - Ottawa Citizen
     - http://www.ottawacitizen.com
   - - Ozarks News
     - http://www.sgfnews.org
   - - PBS News Navigator
     - http://pbs.org
   - - Phawker
     - http://www.phawker.com
   - - Pioneer Press/Sun-Times Media
     - http://www.pioneerlocal.com
   - - Pioneer Press
     - http://twincities.com
   - - Pittsburg Post-Gazette
     - http://post-gazette.com
   - - Politico.ie
     - http://politico.ie
   - - Politifact
     - http://politifact.com/
   - - Press & Sun-Bulletin
     - http://Pressconnects.com
   - - PsychSearch.net
     - http://psychsearch.net/
   - - Public Education Center
     - http://DCBureau.org
   - - Public Radio International
     - http://pri.org
   - - Public Insight Journalism
     - http://americanpublicmedia.org/cij
   - - Public.Resource.Org
     - http://public.resource.org
   - - Rapid City Journal
     - http://www.rapidcityjournal.com/
   - - Reference Tone
     - http://referencetone.com
   - - The Register-Guard
     - http://registerguard.com
   - - Reno Gazette Journal
     - http://www.rgj.com/
   - - Reprieve
     - http://www.reprieve.org.uk
   - - Sacramento Bee
     - http://www.sacbee.com
   - - San Antonio Express-News
     - http://www.mysanantonio.com/
   - - San Diego Reader
     - http://www.sandiegoreader.com
   - - San Diego Union-Tribune
     - http://signonsandiego.com/
   - - San Francisco Chronicle
     - http://www.sfgate.com
   - - San Jose Mercury News
     - http://www.mercurynews.com
   - - Santa Fe Reporter
     - http://sfreporter.com
   - - Sarasota Herald-Tribune
     - http://www.heraldtribune.com
   - - SCOTXblog
     - http://www.scotxblog.com/
   - - Scripps Howard News Service
     - http://shns.com
   - - The Seattle Times
     - http://seattletimes.nwsource.com
   - - SF Public Press
     - http://sfpublicpress.org
   - - The Skanner
     - http://www.theskanner.com
   - - Southern California Public Radio
     - http://www.scpr.org
   - - Spinwatch
     - http://spinwatch.org
   - - Stabile Center for Investigative Journalism
     - http://www.stabilecenter.org/
   - - StarNews
     - http://StarNewsOnline.com
   - - Statesman Journal
     - http://statesmanjournal.com
   - - The Story
     - http://thestory.ie
   - - St. Louis Post-Dispatch
     - http://www.stltoday.com
   - - St. Petersburg Times
     - http://tampabay.com
   - - Sunlight Foundation
     - http://sunlightfoundation.com
   - - TBD
     - http://www.tbd.com/
   - - Texas Observer
     - http://www.texasobserver.org
   - - Texas Tribune
     - http://www.texastribune.com
   - - Thomson Reuters
     - http://thomsonreuters.com
   - - Transactional Records Access Clearinghouse
     - http://trac.syr.edu/
   - - Tucson Sentinel
     - http://www.tucsonsentinel.com/
   - - UBC School of Journalism
     - http://journalism.ubc.ca
   - - Legacy Tobacco Documents Library (UCSF)
     - http://legacy.library.ucsf.edu
   - - USA Today
     - http://www.usatoday.com
   - - US Local News Network
     - http://www.uslnn.com
   - - Vancouver Sun
     - http://vancouversun.com
   - - Voice of San Diego
     - http://voiceofsandiego.org
   - - Voices of Montana
     - http://www.northernbroadcasting.com
   - - Washington Post
     - http://wpost.com
   - - Watchdog Institute
     - http://www.watchdoginstitute.org
   - - Western Citizen
     - http://www.westerncitizen.com
   - - Wichita Eagle
     - http://www.kansas.com/
   - - Wired.com
     - http://www.wired.com
   - - Wisconsin Center for Investigative Journalism
     - http://www.wisconsinwatch.org/
   - - WNYC Radio
     - http://wnyc.org
   - - WTXF Fox 29
     - http://www.foxtv.com
   - - York Daily Record
     - http://www.ydr.com
