<% secrets = YAML.load_file(File.join(Rails.root, 'secrets/secrets.yml'))[ENV['RAILS_ENV'] || 'development'] %>

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5
  username: <%= secrets['username'] %>
  password: <%= secrets['db_password'] %>
  allow_concurrency: true
  host: <%= secrets['db_host'] %>

development:
  <<: *defaults
  database: dcloud_development

staging:
  <<: *defaults
  database: dcloud_staging

production:
  <<: *defaults
  database: dcloud_staging

test:
  <<: *defaults
  database: dcloud_staging
