<% secrets = YAML.load_file('./secrets/secrets.yml')[ENV['RAILS_ENV'] || "development"] %>
defaults: &defaults
  cloud_crowd_server:   http://dev.dcloud.org:9173
  server_root:          dev.dcloud.org
  aws_zone:             us-east-1c
  preconfigured_ami_id: ami-01aae468

development:
  <<: *defaults

staging:
  <<: *defaults
  cloud_crowd_server: dev.dcloud.org:9173
  server_root:        dev.dcloud.org
  asset_root:         "//s3.ipublic.org/dcloud-staging"


production:
  <<: *defaults
  cloud_crowd_server: dev.dcloud.org:9173
  server_root:        dev.dcloud.org
  asset_root:         "s3://dcloud-staging"

test:
  <<: *defaults
  cloud_crowd_server: dev.dcloud.org:9173
  server_root:        dev.dcloud.org
  asset_root:         "//s3.ipublic.org/dcloud-staging"