production:
  solr:
    hostname: localhost
    port: 8983
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

ipublic:
  solr:
    hostname: localhost
    port: 8983
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: ALL
    path: /solr/collection1
    pid_dir: tmp/pids

staging:
  solr:
    hostname: ec2-50-16-197-147.compute-1.amazonaws.com
    port: 7377
    log_level: WARNING
    pid_dir: tmp/pids
    path: /solr/collection1
